[coincidences]
refr = 20                 ; reference frame
cthr = 15.5               ; Fstatistic threshold for coincidences
hemi = 0                  ; hemisphere to consider (1||2||0 for both)
scalef = 32               ; cell scale factor for fbin
scales = 4                ; cell scale factor for s
scalem = 1                ; cell scale factor for m
scalen = 1                ; cell scale factor for n
shift = 0000              ; cell shifts, if empty loop over all 16 permutations
mincoin = 3               ; minimum number of coincidences to write out
out_dir = .                ; output directory, cwd by default
trig_dset = triggers      ; read triggers from this dataset (triggers||injections)
coinc_dset = coinc_        ; write coincidences to dataset: coinc_{shift}
# to add files below use command:
# ls -1 <path>/triggers_*_0017_1.h5 | sed '$!s/$/ \\/' >> coinc-test.ini
trig_file_list = \
file1 \
file2 \
file3
